### ISSUE TITLE
iteration problem on vis.plot_infomap_igraph()

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/IRCLogParser#134]
When we iterate for different channels and different cutoffs, this function enters deadlock.

Possible inputs to unit tests to infer the problem are:

1. small graph from one channel
1. large graph from one channel
1. small graph from two channels
1. large graph from two channels
1. small graph from four channels
1. large graph from four channels.

**Comment by rohangoel96** [comment]
Do we have the script which resulted in deadlock?

**Comment by rohangoel96** [comment]
Do we have the script which resulted in deadlock?

**Comment by kaushik-rohit** [comment]
[25-Sep.txt](https://github.com/prasadtalasila/IRCLogParser/files/1328835/25-Sep.txt)
@rohangoel96 I don't think that changing config variable by assigning is a problem. If you have a look at the above attachment the cutoffs changes correctly. Point to note is these outputs are using print from functions in different files from where the config variable was changed.

**Comment by rohangoel96** [comment]
@kaushik-rohit Alright! I will try and see if I can recreate the scenario and fix it.

**Comment by kaushik-rohit** [comment]
@rohangoel96 Our main objective here is to run analysis for different cut-offs/ different dates in a single run. We can obviously change to better config and it has been discussed as well. But for now that may take more time since we will need to change lot many lines due to config variable being used at many places. In case you come up with different solution which solve our main objective, I guess that will also be fine.

**Comment by rohangoel96** [comment]
@kaushik-rohit Yeah i understand !

**Comment by prasadtalasila** [comment]
Based on recent emails of @kaushik-rohit, we can assume that this code to be working properly. If working is confirmed, we can postpone creation of unit tests until after the paper is sent.

**Comment by prasadtalasila** [comment]
@kaushik-rohit Is this issue resolved? If so, please close this issue.
