### ISSUE TITLE
create / update unit tests for util and vis modules

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/IRCLogParser#190]
Create and update unit tests for lib/util and lib/vis modules. We need to follow parameterized test patterns used in functional tests.

**Comment by kaushik-rohit** [comment]
@prasadtalasila Can you please explain what you mean by parameterized test patterns here? Also do we need to introduce more test or update the current ones.

**Comment by prasadtalasila** [comment]
Please see lines [67-73](https://github.com/prasadtalasila/IRCLogParser/blob/dev/test/tests.py#L67-L73) for an example of parameterized test.

**Comment by kaushik-rohit** [comment]
@prasadtalasila We already have tests for util under /test/unit_tests.py and I don't think converting them to parameterized test gives us any advantage here since these test don't run on log data but some intermediate result, even if we modify it to parameterized tests the parameters are going to be a long list for different version of arguments and that is rather not useful. I wrote the test as parameterized test only in-case of end-to-end testing. Do you see any specific advantage here with adoption of parameterized tests?

**Comment by kaushik-rohit** [comment]
@prasadtalasila The last comment also holds true for vis tests. I don't thinks parameterization is helpful in unittest. In end-to-end test this gives us advantage of reducing code duplication since ddt helps us here in running the same code for different logs. 

Although, We need to include more test which are not covered for newer functions introduced or those for which unit-test were not written in earlier cycle.

**Comment by prasadtalasila** [comment]
parameterized unit tests for util.py module have been committed.

**Comment by prasadtalasila** [comment]
@bhuvangupta008 please work on this issue.
