### ISSUE TITLE
Integration tests for lib.analysis.network module

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/IRCLogParser#280]
The following functions of the module need integration tests.
1. lib.analysis.network.degree_node_number_csv()
1. lib.analysis.network.identify_hubs_and_experts()
1. lib.analysis.network.message_number_graph()
1. lib.analysis.network.message_number_bins_csv()
1. lib.analysis.network.message_time_graph()

**Comment by prasadtalasila** [comment]
@kaushik-rohit The PR #291 has been merged with the dev branch, but the build fails. Please send in another PR to fix the problem.

**Comment by kaushik-rohit** [comment]
@prasadtalasila There seems to some problem with the vis tests.
@bhuvangupta008 can you please look into it.

**Comment by prasadtalasila** [comment]
* lines 522-527 of the lib/analysis/network.py module needs to be covered.
* network.py of slack channel needs to be covered as well.

**Comment by kaushik-rohit** [comment]
@prasadtalasila Sir, I haven't written integration test for **degree_analysis_on_graph** since it wasn't mentioned in the suggestions. The line 522-527 is part of **degree_analysis_on_graph**, the reason why part of the function show test coverage is because it is being used in **degree_node_number_csv** which uses degree analysis on message_number_graph (directed graph only).
