### ISSUE TITLE
code review of all the existing tests

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/IRCLogParser#304]
The existing integration and unit tests need to be reviewed for consistency and correctness. Any problems detected can be discussed in this issue thread.

**Comment by kaushik-rohit** [comment]
I will keep on updating the list. 
1) (Not Needed) <del> Rather than using current directory every time, we can define test_data_dir as done in other tests.</del>
https://github.com/prasadtalasila/IRCLogParser/blob/dev/test/unit-test/test_lib/test_nickTracker.py#L26 
2) <del> Would be better if config mocks are at the top. </del>
- https://github.com/prasadtalasila/IRCLogParser/blob/dev/test/unit-test/test_lib/test_nickTracker.py#L23
- https://github.com/prasadtalasila/IRCLogParser/blob/master/test/unit-test/test_lib/test_analysis/test_user.py#L116
- https://github.com/prasadtalasila/IRCLogParser/blob/master/test/unit-test/test_lib/test_analysis/test_user.py#L154
3) These two functions should not be introduced as side_effect, rather caching of result should be used as done in other tests to maintain consistency.
- https://github.com/prasadtalasila/IRCLogParser/blob/dev/test/unit-test/test_lib/test_util.py#L20
4) <del> Global variable use here. Should be moved to setUp. </del> 
- https://github.com/prasadtalasila/IRCLogParser/blob/dev/test/unit-test/test_lib/test_in_out/test_reader.py#L10
- https://github.com/prasadtalasila/IRCLogParser/blob/dev/test/unit-test/test_lib/test_analysis/test_channel.py#L6
- https://github.com/prasadtalasila/IRCLogParser/blob/dev/test/unit-test/test_slack/test_lib/test_analysis/test_channel.py#L8
5) <del> Naming convention not followed. Change to expected_log_data. </del>
- Here: https://github.com/prasadtalasila/IRCLogParser/blob/dev/test/unit-test/test_lib/test_in_out/test_reader.py#L83
- https://github.com/prasadtalasila/IRCLogParser/blob/dev/test/unit-test/test_lib/test_analysis/test_network.py#L216
6) <del> Use self.assert* to maintain consistency. </del>
- https://github.com/prasadtalasila/IRCLogParser/blob/dev/test/unit-test/test_lib/test_analysis/test_community.py#L29
- https://github.com/prasadtalasila/IRCLogParser/blob/dev/test/unit-test/test_lib/test_analysis/test_channel.py#L30
- https://github.com/prasadtalasila/IRCLogParser/blob/dev/test/unit-test/test_slack/test_lib/test_util.py#L182
- https://github.com/prasadtalasila/IRCLogParser/blob/dev/test/unit-test/test_slack/test_lib/test_nicktracker.py#L23
- https://github.com/prasadtalasila/IRCLogParser/blob/dev/test/unit-test/test_slack/test_lib/test_analysis/test_channel.py#L32
- https://github.com/prasadtalasila/IRCLogParser/blob/dev/test/unit-test/test_scummvm/test_lib/test_nicktracker.py#L22
https://github.com/prasadtalasila/IRCLogParser/blob/dev/test/integration-test/test_lib/test_vis.py#L22

7) <del> Move these tests to correct file. </del>
- https://github.com/prasadtalasila/IRCLogParser/blob/dev/test/unit-test/test_slack/test_functional.py

**Comment by prasadtalasila** [comment]
@bhuvangupta008 and @Kausam Please look at the above list and corroborate / update the suggestions. @kaushik-rohit is about to start work on these topics; it would be helpful to have your opinion soon.

**Comment by Kausam** [comment]
@kaushik-rohit, I will fix issue 1 if you are not already working on it.

**Comment by kaushik-rohit** [comment]
@Kausam ok, you can do that but I later realized it wouldn't be any better to introduce a new variable and use it and hence didn't change it.

**Comment by Kausam** [comment]
@kaushik-rohit  so it means that the change is not required, right? Let's remove that from the list.
