### ISSUE TITLE
use config object (dictionary) instead of config.py and better arguments for functions

### ISSUE THREAD

**Issue by rohangoel96** [prasadtalasila/IRCLogParser#84]
^ industry standard
the config object can be passed to functions as an argument
config.py should be completely done away with

**Comment by rohangoel96** [comment]
@krishnacharya you should do this asap

**Comment by rohangoel96** [comment]
more help: https://pythontips.com/2013/08/04/args-and-kwargs-in-python-explained/
http://book.pythontips.com/en/latest/args_and_kwargs.html

**Comment by prasadtalasila** [comment]
It does make sense to use sensible defaults for non-essential arguments. Instead of overwhelming the user with a requirement to specify all configuration parameters, we can have a default configuration dictionary object in the library.

We can then separate all the configuration into mandatory and optional categories. All the functions throw up errors if the mandatory arguments are missing. If the optional arguments are missing, the default ones from library config are taken.

Considering that the user is likely to run the analysis from a directory, we can have the user place a config.py / config properties in a python standard convention in the current directory. Using a persistent properties / configuration file makes it easier to run / rerun the analysis in an automated way.

**Comment by prasadtalasila** [comment]
Also checkout a [relevant issue](https://github.com/DeveloperCAP/MLCAT/issues/91).

This is not a priority for now.
